FROM python:3.12-slim
LABEL authors="jacktoke"

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

COPY ./dashboard/ .

RUN mkdir -p /app/data/staging

COPY ./data/staging/realestate.duckdb /app/data/staging/realestate.duckdb

COPY ./streamlit_requirements.txt ./requirements.txt

RUN pip install -r requirements.txt