FROM python:3.12-slim

RUN pip install \
  dagster \
  dagster-graphql \
  dagster-webserver \
  dagster-duckdb \
  dagster-dbt \
  dagster-duckdb-pandas \
  dagster-docker \
  dagster-postgres

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY workspace.yaml dagster.yaml .env $DAGSTER_HOME

WORKDIR $DAGSTER_HOME

ENTRYPOINT [ "dagster-daemon", "run"]