version: 2

models:
  - name: fct_sold_listing
    description: Fact table for sold listings
    config:
      meta:
        dagster:
          group: DBT_FACT_DATA
  - name: fct_active_listing
    description: Fact table for active listings
    config:
      meta:
        dagster:
          group: DBT_FACT_DATA