version: 2

models:
  - name: stg_suburbs
    description: The suburbs table, cleaned and decoded
    config:
      meta:
        dagster:
          group: DBT_STAGING_DATA
    columns:
      - name: suburb_id
        description: The identifying code of a suburb
      - name: suburb_name
        description: The name of the suburb
      - name: urban_area
        description: The name of the area the suburb is in
      - name: postcode
        description: The four digit postcode
      - name: state_code
        description: The abbreviated code of the state
      - name: state_name
        description: The fullname of the state
      - name: suburb_type
        description: The type of the suburb
      - name: local_government_area
        description: The name of the city council in which the suburb is located
      - name: statistic_area
        description: The name of the area for statistic purpose
      - name: elevation
        description: The elevation above sea level
      - name: population
        description: The number of people living in the suburb
      - name: median_income
        description: The median income of the population
      - name: sqkm
        description: The square kilometers (or the size) of the suburb
      - name: lat
        description: The latitude of the suburb
      - name: lng
        description: The longitude of the suburb
      - name: timezone
        description: The timezone of the suburb/state
  - name: stg_addresses
    config:
      meta:
        dagster:
          group: DBT_STAGING_DATA
  - name: stg_agencies
    config:
      meta:
        dagster:
          group: DBT_STAGING_DATA
  - name: stg_agents
    config:
      meta:
        dagster:
          group: DBT_STAGING_DATA
  - name: stg_listing_agents
    config:
      meta:
        dagster:
          group: DBT_STAGING_DATA
  - name: stg_listing_features
    config:
      meta:
        dagster:
          group: DBT_STAGING_DATA
  - name: stg_listings
    config:
      meta:
        dagster:
          group: DBT_STAGING_DATA
  - name: stg_rental_listings
    config:
      meta:
        dagster:
          group: DBT_STAGING_DATA